-- require("kevinhwang91/rnvimr").setup {
-- -- Make Ranger replace Netrw and be the file explorer
-- rnvimr_enable_ex = 1;
-- -- Make Ranger to be hidden after picking a file
-- rnvimr_enable_picker = 1;
-- -- Replace `$EDITOR` candidate with this command to open the selected file
-- rnvimr_edit_cmd = 'drop';
-- -- Disable a border for floating window
-- rnvimr_draw_border = 0;
-- -- Hide the files included in gitignore
-- rnvimr_hide_gitignore = 1;
-- -- Change the border's color
-- -- rnvimr_border_attr = {'fg': 14, 'bg': -1};
-- -- Make Neovim wipe the buffers corresponding to the files deleted by Ranger
-- rnvimr_enable_bw = 1;
-- -- Add a shadow window, value is equal to 100 will disable shadow
-- rnvimr_shadow_winblend = 70;
-- -- Draw border with both
-- -- rnvimr_ranger_cmd = ['ranger', '--cmd=set draw_borders both'];
-- }